version: "3"
services:
    jaegertracing1:
        image: jaegertracing/all-in-one:latest
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
            - COLLECTOR_OTLP_ENABLED=true
        ports:
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16685:16685
            - 16686:16686
            - 14268:14268
            - 14269:14269
            - 14250:14250
            - 9411:9411
            - 4317:4317
            - 4318:4318
    postgres1:
        image: postgres:latest
        container_name: postgres1
        networks: ["deimos-api"]
        ports:
            - "5432:5432"
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
networks:
    deimos-api:
        name: deimos-api
        driver: bridge
